{
 "title": "tado° Dashboard",
 "description": "Grafana Dashboard that shows the temperature setting, current temperature, humidity and activity for all rooms. A detailed view is shown based on the selected room.",
 "tags": [
  "tado",
  "casa"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "zone",
    "label": "Zones",
    "query": "SHOW TAG VALUES from dAm2KTADO_Zones with key=\"zonename\""
   }
  ]
 },
 "panels": [
  {
   "title": "Zone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperatura e umidità: $zone",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "repeat": "zone",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "legendFormat": "Current Temperature",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "celsius" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    },
    {
     "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "legendFormat": "Current Temperature",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "description": "temperature",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
   "options": {
    "content": "<span style=\"font-size:32px\">Temperatura</span>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "celsius" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Gestione riscaldamento",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tado_activity_heating_power_percentage{zone=\"$zone\"}",
     "legendFormat": "Heating Power",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "controltype" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 19 },
   "options": {
    "content": "<span style=\"font-size:32px\">Umidità</span>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "celsius" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "alias": "Min",
     "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "legendFormat": "Min:",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "celsius" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "legendFormat": "Min:",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tado_activity_heating_power_percentage{zone=\"$zone\"}",
     "legendFormat": "Heating Power",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "legendFormat": "Max:",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "celsius" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperatura desiderata",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tado_setting_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "legendFormat": "Set Temperature",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "desired_celsius" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "legendFormat": "Max:",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "legendFormat": "Avg:",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "celsius" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Spinta riscaldamento",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tado_setting_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
     "legendFormat": "Set Temperature",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "heating_power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "legendFormat": "Avg:",
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "zonename::tag", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Tutte le zone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperatura desiderata: Tutte le zone",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "tado_activity_heating_power_percentage",
     "groupBy": [
      { "params": [ "zonename::tag" ], "type": "tag" }
     ],
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "desired_celsius" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Termostato",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tado_activity_heating_power_percentage",
     "groupBy": [
      { "params": [ "zonename::tag" ], "type": "tag" }
     ],
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "desired_celsius" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spinta riscaldamento: Tutte le zone",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tado_activity_heating_power_percentage",
     "groupBy": [
      { "params": [ "zonename::tag" ], "type": "tag" }
     ],
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "heating_power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spinta riscaldamento",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tado_activity_heating_power_percentage",
     "groupBy": [
      { "params": [ "zonename::tag" ], "type": "tag" }
     ],
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "heating_power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature: Tutte le zone",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{unit=\"celsius\"}",
     "groupBy": [
      { "params": [ "zonename::tag" ], "type": "tag" }
     ],
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "celsius" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tado_activity_heating_power_percentage",
     "groupBy": [
      { "params": [ "zonename::tag" ], "type": "tag" }
     ],
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "celsius" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Umidità: Tutte le zone",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{unit=\"celsius\"}",
     "groupBy": [
      { "params": [ "zonename::tag" ], "type": "tag" }
     ],
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Umidità",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tado_activity_heating_power_percentage",
     "groupBy": [
      { "params": [ "zonename::tag" ], "type": "tag" }
     ],
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Dispositivi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Lista dispositivi TADO",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "zonename::tag" ], "type": "tag" }
     ],
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "shortSerialNo" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "serialNo::tag" ], "type": "tag" },
      { "params": [ "zonename::tag" ], "type": "tag" },
      { "params": [ "zonetype::tag" ], "type": "tag" }
     ],
     "measurement": "dAm2KTADO_Zones",
     "select": [
      [
       { "params": [ "batteryState" ], "type": "field" }
      ],
      [
       { "params": [ "shortSerialNo" ], "type": "field" }
      ],
      [
       { "params": [ "deviceType" ], "type": "field" }
      ],
      [
       { "params": [ "connectionState" ], "type": "field" }
      ],
      [
       { "params": [ "currentFwVersion" ], "type": "field" }
      ],
      [
       { "params": [ "mountingState" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}